create extension if not exists pgcrypto with schema extensions;

create table if not exists public.lan_agents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  status text not null default 'offline' check (status in ('online','offline')),
  lan_ip inet,
  public_ip inet,
  tailscale_ip inet,
  platform text,
  agent_version text,
  capabilities jsonb not null default '{}'::jsonb,
  last_latency_ms integer check (last_latency_ms is null or last_latency_ms >= 0),
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists lan_agents_user_id_idx on public.lan_agents(user_id);
create index if not exists lan_agents_last_seen_idx on public.lan_agents(last_seen_at desc);

create table if not exists public.lan_agent_credentials (
  agent_id uuid primary key references public.lan_agents(id) on delete cascade,
  token_hash text not null unique check (char_length(token_hash) = 64),
  created_at timestamptz not null default now(),
  last_rotated_at timestamptz not null default now()
);

create table if not exists public.lan_pairing_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  code_hash text not null unique check (char_length(code_hash) = 64),
  expires_at timestamptz not null,
  claimed_at timestamptz,
  agent_id uuid references public.lan_agents(id) on delete set null,
  created_at timestamptz not null default now(),
  check (expires_at > created_at)
);
create index if not exists lan_pairing_requests_user_id_idx on public.lan_pairing_requests(user_id, created_at desc);
create index if not exists lan_pairing_requests_expires_idx on public.lan_pairing_requests(expires_at);

create table if not exists public.lan_proxies (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null references public.lan_agents(id) on delete cascade,
  host inet not null,
  port integer not null check (port between 1 and 65535),
  protocol text not null check (protocol in ('http','https','socks5')),
  enabled boolean not null default true,
  healthy boolean not null default false,
  latency_ms integer check (latency_ms is null or latency_ms >= 0),
  last_checked_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(agent_id, host, port, protocol)
);
create index if not exists lan_proxies_agent_id_idx on public.lan_proxies(agent_id);

create table if not exists public.lan_agent_commands (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null references public.lan_agents(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  command_type text not null check (command_type in ('rescan','validate_proxy','set_proxy_enabled','rename_agent')),
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'queued' check (status in ('queued','acknowledged','completed','failed')),
  created_at timestamptz not null default now(),
  acknowledged_at timestamptz,
  completed_at timestamptz,
  error_message text
);
create index if not exists lan_agent_commands_agent_queue_idx on public.lan_agent_commands(agent_id, status, created_at);

create table if not exists public.lan_agent_events (
  id bigint generated by default as identity primary key,
  agent_id uuid not null references public.lan_agents(id) on delete cascade,
  event_type text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.lan_agents enable row level security;
alter table public.lan_agent_credentials enable row level security;
alter table public.lan_pairing_requests enable row level security;
alter table public.lan_proxies enable row level security;
alter table public.lan_agent_commands enable row level security;
alter table public.lan_agent_events enable row level security;

create policy "lan_agents_select_own" on public.lan_agents for select to authenticated using (user_id = auth.uid());
create policy "lan_pairing_select_own" on public.lan_pairing_requests for select to authenticated using (user_id = auth.uid());
create policy "lan_pairing_delete_own" on public.lan_pairing_requests for delete to authenticated using (user_id = auth.uid() and claimed_at is null);
create policy "lan_proxies_select_own" on public.lan_proxies for select to authenticated using (exists (select 1 from public.lan_agents a where a.id = lan_proxies.agent_id and a.user_id = auth.uid()));
create policy "lan_commands_select_own" on public.lan_agent_commands for select to authenticated using (user_id = auth.uid());
create policy "lan_commands_insert_own" on public.lan_agent_commands for insert to authenticated with check (user_id = auth.uid() and exists (select 1 from public.lan_agents a where a.id = lan_agent_commands.agent_id and a.user_id = auth.uid()));
create policy "lan_events_select_own" on public.lan_agent_events for select to authenticated using (exists (select 1 from public.lan_agents a where a.id = lan_agent_events.agent_id and a.user_id = auth.uid()));

create or replace function public.lan_create_pairing_key()
returns table(pairing_key text, expires_at timestamptz)
language plpgsql security definer set search_path = public, extensions as $$
declare v_user uuid := auth.uid(); v_code text; v_exp timestamptz := now() + interval '10 minutes';
begin
  if v_user is null then raise exception 'authentication required'; end if;
  delete from public.lan_pairing_requests where user_id = v_user and claimed_at is null and expires_at < now();
  v_code := upper(substr(encode(extensions.gen_random_bytes(8), 'hex'), 1, 12));
  insert into public.lan_pairing_requests(user_id, code_hash, expires_at)
  values (v_user, encode(extensions.digest(v_code, 'sha256'), 'hex'), v_exp);
  return query select v_code, v_exp;
end; $$;
revoke all on function public.lan_create_pairing_key() from public;
grant execute on function public.lan_create_pairing_key() to authenticated;

create or replace function public.lan_claim_pairing(p_pairing_key text,p_agent_name text,p_platform text,p_agent_version text,p_capabilities jsonb,p_token_hash text)
returns uuid language plpgsql security definer set search_path = public, extensions as $$
declare v_pair public.lan_pairing_requests%rowtype; v_agent_id uuid;
begin
  if char_length(coalesce(p_token_hash,'')) <> 64 then raise exception 'invalid token hash'; end if;
  select * into v_pair from public.lan_pairing_requests
  where code_hash = encode(extensions.digest(upper(trim(p_pairing_key)), 'sha256'), 'hex') and claimed_at is null and expires_at > now()
  order by created_at desc limit 1 for update;
  if v_pair.id is null then raise exception 'invalid or expired pairing key'; end if;
  insert into public.lan_agents(user_id,name,platform,agent_version,capabilities,status)
  values(v_pair.user_id,left(coalesce(nullif(trim(p_agent_name),''),'LAN Agent'),80),left(coalesce(p_platform,''),80),left(coalesce(p_agent_version,''),40),coalesce(p_capabilities,'{}'::jsonb),'offline')
  returning id into v_agent_id;
  insert into public.lan_agent_credentials(agent_id,token_hash) values(v_agent_id,lower(p_token_hash));
  update public.lan_pairing_requests set claimed_at=now(),agent_id=v_agent_id where id=v_pair.id;
  insert into public.lan_agent_events(agent_id,event_type,detail) values(v_agent_id,'paired',jsonb_build_object('platform',p_platform,'agent_version',p_agent_version));
  return v_agent_id;
end; $$;
revoke all on function public.lan_claim_pairing(text,text,text,text,jsonb,text) from public, anon, authenticated;
grant execute on function public.lan_claim_pairing(text,text,text,text,jsonb,text) to service_role;

grant select on public.lan_agents, public.lan_pairing_requests, public.lan_proxies, public.lan_agent_commands, public.lan_agent_events to authenticated;
grant insert on public.lan_agent_commands to authenticated;
grant delete on public.lan_pairing_requests to authenticated;

do $$ begin alter publication supabase_realtime add table public.lan_agents; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.lan_proxies; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.lan_agent_commands; exception when duplicate_object then null; end $$;
